<a href="https://colab.research.google.com/github/Kashishkewat/python_practice/blob/main/day15_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas**

---

1. pandas is a powerful and popular pyhton library esigned for data manipulation(cleaning ,tranforming and stucturing data)and data analysis (finding patterns ,trends and insights).
 2.  it simplifiles working with structured datasets like tables,preadsheets,or time-series data.

# **key  pandas concepts**

# **1.series:**


*   a series is a one dimensional labeled array that can hold any data type: integers,floats ,strings ,or even python objects .Each element in the series has a unique labelcalled an index
*   it is often to track changes or patterns over time ,such as daily temperatures ,stock prices or sales revenue.

# **2.DataFrame:**


*   A dataframe is a two dimensional labeled data structure in pandas ,similar to a table in a database ,an excel,spreadsheet,or a SQL table.
*  It consists of rows and columns ,where:


1.   rows have indices(labels).
2.   columns have names(labels).

In [1]:
import pandas as pd

In [2]:
from google.colab import files
uploaded=files.upload()

Saving Exam_Score_Prediction.csv to Exam_Score_Prediction.csv

In [3]:
#read data from CSV file into a dataframe
#df=pd.read_excel("sample.xlsx")
df=pd.read_csv("Exam_Score_Prediction.csv")

In [4]:
print(df)

       student_id  age  gender   course  study_hours  class_attendance  \
0               1   17    male  diploma         2.78              92.9
1               2   23   other      bca         3.37              64.8
2               3   22    male     b.sc         7.88              76.8
3               4   20   other  diploma         0.67              48.4
4               5   20  female  diploma         0.89              71.6
...           ...  ...     ...      ...          ...               ...
19995       19997   18   other      bba         6.50              71.3
19996       19998   18    male    b.com         3.71              41.6
19997       19999   19   other  diploma         7.88              68.2
19998       20000   19    male      bba         4.60              76.3
19999       20001   20    male     b.sc         7.50              47.9

      internet_access  sleep_hours sleep_quality   study_method  \
0                 yes          7.4          poor       coaching
1                 yes          4.6       average  online videos
2                 yes          8.5          poor       coaching
3                 yes          5.8       average  online videos
4                 yes          9.8          poor       coaching
...               ...          ...           ...            ...
19995             yes          5.0          good     self-study
19996              no          5.9       average       coaching
19997             yes          4.6          poor    group study
19998              no          6.1          good     self-study
19999             yes          7.5          poor       coaching

      facility_rating exam_difficulty  exam_score
0                 low            hard        58.9
1              medium        moderate        54.8
2                high        moderate        90.3
3                 low        moderate        29.7
4                 low        moderate        43.7
...               ...             ...         ...
19995             low            easy        86.5
19996          medium        moderate        60.9
19997             low            easy        64.5
19998          medium        moderate        79.0
19999          medium        moderate        71.0

[20000 rows x 13 columns]

In [5]:
first=df['age']
print(first.head())

0    17
1    23
2    22
3    20
4    20
Name: age, dtype: int64

In [6]:
#how creating dataframe
data={
    "name":["ram","shyam","joe","sonu"],
    "age":[13,14,15,16],
    "city":["indore","barwaha","mumbai","nagpur"]
}

In [7]:
df1=pd.DataFrame(data)
print(df1)

    name  age     city
0    ram   13   indore
1  shyam   14  barwaha
2    joe   15   mumbai
3   sonu   16   nagpur

In [8]:
df1.to_csv("output.csv",index=False)
#df.to_excel("output.xlsx",index=False)

In [9]:
df.head(3)# display starting 3 row of data by default show 5 row

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3

In [10]:
df.tail(3)# display last 5 row of dataframe

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
19997,19999,19,other,diploma,7.88,68.2,yes,4.6,poor,group study,low,easy,64.5
19998,20000,19,male,bba,4.60,76.3,no,6.1,good,self-study,medium,moderate,79.0
19999,20001,20,male,b.sc,7.50,47.9,yes,7.5,poor,coaching,medium,moderate,71.0

In [11]:
df.info()# structure & datatypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        20000 non-null  int64
 1   age               20000 non-null  int64
 2   gender            20000 non-null  object
 3   course            20000 non-null  object
 4   study_hours       20000 non-null  float64
 5   class_attendance  20000 non-null  float64
 6   internet_access   20000 non-null  object
 7   sleep_hours       20000 non-null  float64
 8   sleep_quality     20000 non-null  object
 9   study_method      20000 non-null  object
 10  facility_rating   20000 non-null  object
 11  exam_difficulty   20000 non-null  object
 12  exam_score        20000 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 2.0+ MB

In [12]:
df.describe()# statistics

,student_id,age,study_hours,class_attendance,sleep_hours,exam_score
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000
mean,10000.504600,20.473300,4.007604,70.017365,7.00856,62.513225
std,5773.654959,2.284458,2.308313,17.282262,1.73209,18.908491
min,1.000000,17.000000,0.080000,40.600000,4.10000,19.599000
25%,5000.750000,18.000000,2.000000,55.100000,5.50000,48.800000
50%,10000.500000,20.000000,4.040000,69.900000,7.00000,62.600000
75%,15000.250000,22.000000,6.000000,85.000000,8.50000,76.300000
max,20001.000000,24.000000,7.910000,99.400000,9.90000,100.000000

In [13]:
import numpy as np#Creating DataFrame from dict of Numpy Array
import pandas as pd

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(data, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [14]:
# initialize list of lists
data = [['tom', 10], ['nick', 15], ['juli', 14]]

# Create the pandas DataFrame
df = pd.DataFrame(data, columns=['Name', 'Age'])

print(df)

   Name  Age
0   tom   10
1  nick   15
2  juli   14

In [15]:
# Accessing and Modifying the Index
data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df2= pd.DataFrame(data)
print(df.index)  # Accessing the index

RangeIndex(start=0, stop=3, step=1)

In [16]:
# Set 'Name' column as the index
df_with_index = df2.set_index('Name')
print(df_with_index)

         Age  Gender  Salary
Name
John      25    Male   50000
Alice     30  Female   55000
Bob       22    Male   40000
Eve       35  Female   70000
Charlie   28    Male   48000

In [17]:
# Reset the index back to the default integer index
df_reset = df2.reset_index()
print(df_reset)

   index     Name  Age  Gender  Salary
0      0     John   25    Male   50000
1      1    Alice   30  Female   55000
2      2      Bob   22    Male   40000
3      3      Eve   35  Female   70000
4      4  Charlie   28    Male   48000

In [18]:
row = df_with_index.loc['Alice']
print(row)

Age           30
Gender    Female
Salary     55000
Name: Alice, dtype: object

In [19]:
# Set 'Age' as the new index
df_with_new_index = df2.set_index('Age')
print(df_with_new_index)

        Name  Gender  Salary
Age
25      John    Male   50000
30     Alice  Female   55000
22       Bob    Male   40000
35       Eve  Female   70000
28   Charlie    Male   48000

In [20]:
# Access the 'Age' column
age_column = df2['Age']
print(age_column)

0    25
1    30
2    22
3    35
4    28
Name: Age, dtype: int64

In [21]:
# Access the row at index 1 (second row)
second_row = df2.iloc[1]
print(second_row)

Name       Alice
Age           30
Gender    Female
Salary     55000
Name: 1, dtype: object

In [22]:
# Access the first three rows and the 'Name' and 'Age' columns
subset = df2.loc[0:2, ['Name', 'Age']]
print(subset)

    Name  Age
0   John   25
1  Alice   30
2    Bob   22

In [23]:
# Access rows where 'Age' is greater than 25
filtered_data = df2[df2['Age'] > 25]
print(filtered_data)

      Name  Age  Gender  Salary
1    Alice   30  Female   55000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [24]:
salary_data=df2[df2['Salary']>50000]
print(salary_data)

    Name  Age  Gender  Salary
1  Alice   30  Female   55000
3    Eve   35  Female   70000

In [25]:
sd=df2.at[2,"Salary"]
print(sd)

40000

In [26]:
#Slicing Pandas Dataframe

player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

df3 = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
print(df3)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

In [27]:
df_1= df3.iloc[0:4]
print(df_1)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000

In [28]:
df_2= df3.iloc[:, 0:2]

print(df_2)

            Name  Age
0      M.S.Dhoni   36
1  A.B.D Villers   38
2        V.Kohli   31
3        S.Smith   34
4        C.Gayle   40
5         J.Root   33
6     K.Peterson   42

In [32]:
value = df3.iloc[2, 3]
print("Specific Cell Value:", value)

Specific Cell Value: 8428000

In [33]:
data = df[df['Age'] > 35].iloc[:, :]
print("\nFiltered Data based on Age > 35:\n", data)

Filtered Data based on Age > 35:
 Empty DataFrame
Columns: [Name, Age]
Index: []

In [34]:
# import module
#Filter Pandas Dataframe with multiple conditions
import pandas as pd

# assign data
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],

                          'Age': [30, 35, 37, 33, 34, 30],

                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],

                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

# display dataframe
display(dataFrame)

         Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
1    MONICA     35   93000         CHEF
2    PHOEBE     37   88000        MASUS
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST

In [30]:

import pandas as pd

# assign data
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],

                          'Age': [30, 35, 37, 33, 34, 30],

                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],

                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})
# filter dataframe
display(dataFrame.loc[(dataFrame['Salary']>=100000) & (dataFrame['Age']< 40) & (dataFrame['JOB'].str.startswith('D')),
                    ['Name','JOB']])

        Name       JOB
0   RACHEL    DESIGNER

In [45]:
#Concatenating DataFrame using .concat()

data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}

data2 = {'Name': ['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
         'Age': [17, 14, 12, 52],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}

df5= pd.DataFrame(data1, index=[0, 1, 2, 3])

df6= pd.DataFrame(data2, index=[4, 5, 6, 7])

print(df5, "\n\n", df6)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [48]:
frames = [df5, df6]

res1 = pd.concat(frames)
res1

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [56]:
#Sorting a DataFrame by a Single Column
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Name',ascending=True)
print(sorted_df)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [57]:
# importing pandas
import pandas as pd

# creating dataframe
df = pd.DataFrame({'Product': ['Carrots', 'Broccoli', 'Banana', 'Banana',
                               'Beans', 'Orange', 'Broccoli', 'Banana'],
                   'Category': ['Vegetable', 'Vegetable', 'Fruit', 'Fruit',
                                'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
                   'Quantity': [8, 5, 3, 4, 5, 9, 11, 8],
                   'Amount': [270, 239, 617, 384, 626, 610, 62, 90]})
df

    Product   Category  Quantity  Amount
0   Carrots  Vegetable         8     270
1  Broccoli  Vegetable         5     239
2    Banana      Fruit         3     617
3    Banana      Fruit         4     384
4     Beans  Vegetable         5     626
5    Orange      Fruit         9     610
6  Broccoli  Vegetable        11      62
7    Banana      Fruit         8      90

In [59]:
#Create a Pivot Table in Pandas
pivot = df.pivot_table(index=['Product'],
                       values=['Amount'],
                       aggfunc='sum')
print(pivot)

          Amount
Product
Banana      1091
Beans        626
Broccoli     301
Carrots      270
Orange       610

In [61]:
# creating pivot table of total
# sales category-wise aggfunc = 'sum'
pivot = df.pivot_table(index=['Category'],
                       values=['Amount'],
                       aggfunc='sum')
print(pivot)

           Amount
Category
Fruit        1701
Vegetable    1197

In [62]:
# 'mean', 'min'} will get median, mean and
# minimum of sales respectively
pivot = df.pivot_table(index=['Category'], values=['Amount'],
                       aggfunc={'median', 'mean', 'min'})
print(pivot)

           Amount
             mean median min
Category
Fruit      425.25  497.0  90
Vegetable  299.25  254.5  62

# **Series in python**

In [63]:
import pandas as pd

ser = pd.Series()

print(ser)

Series([], dtype: object)

In [67]:
import pandas as pd
import numpy as np

data = np.array(['4', '5', '6', '7', '8'])

ser = pd.Series(data)
print(ser)

0    4
1    5
2    6
3    7
4    8
dtype: object

In [66]:

data_list = ['3', '9', '7', '3', '9']

ser = pd.Series(data_list)
print(ser)

0    3
1    9
2    7
3    3
4    9
dtype: object

In [68]:
data_dict = {'red': 10, 'yellow': 20, 'green': 30}

ser = pd.Series(data_dict)
print(ser)

red       10
yellow    20
green     30
dtype: int64

In [69]:
ser = pd.Series(np.linspace(1, 10, 5))
print(ser)

0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64

In [70]:
d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

mv = df.isnull()

print(mv)

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [71]:
data = {'Name': ['Amit', 'Sita', np.nan, 'Raj'],
        'Age': [25, np.nan, 22, 28]}

df = pd.DataFrame(data)

# Check for missing values using isna()
print(df.isna())

    Name    Age
0  False  False
1  False   True
2   True  False
3  False  False

In [72]:
d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

nmv = df.notnull()

print(nmv)

   First Score  Second Score  Third Score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

In [73]:
d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

df.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [75]:
dict = {'First Score': [100, np.nan, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, np.nan, 80, 98],
        'Fourth Score': [60, 67, 68, 65]}
df = pd.DataFrame(dict)

df.dropna()

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0         52.0            60
3         95.0          56.0         98.0            65

In [76]:
data = {
    "Name": ["Alice", "Bob", "Alice", "David"],
    "Age": [25, 30, 25, 40],
    "City": ["NY", "LA", "NY", "Chicago"]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df_cleaned = df.drop_duplicates()

print("\nModified DataFrame (no duplicates)")
print(df_cleaned)

Original DataFrame:
    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
2  Alice   25       NY
3  David   40  Chicago

Modified DataFrame (no duplicates)
    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

In [77]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Alice", "David", "Bob"],
    "Age": [25, 30, 25, 40, 30],
    "City": ["NY", "LA", "NY", "Chicago", "LA"]
}

df = pd.DataFrame(data)

df_cleaned = df.drop_duplicates(subset=["Name", "City"])

print(df_cleaned)

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

In [78]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)

# Convert 'Age' column to float type
df['Age'] = df['Age'].astype(float)
print(df.dtypes)

Name       object
Age       float64
Gender     object
Salary      int64
dtype: object

# **mini project**

In [79]:
import pandas as pd

data = {
    "Name": ["Amit", "Riya", "Karan", "Neha", "Sonal"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 92, 78, 88, 95],
    "Course": ["CS", "IT", "CS", "IT", "CS"]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Marks Course
0   Amit   20     85     CS
1   Riya   21     92     IT
2  Karan   19     78     CS
3   Neha   22     88     IT
4  Sonal   20     95     CS

In [80]:
avg_marks = df["Marks"].mean()
print("Average Marks:", avg_marks)

Average Marks: 87.6

In [81]:
course_avg = df.groupby("Course")["Marks"].mean()
print(course_avg)

Course
CS    86.0
IT    90.0
Name: Marks, dtype: float64

In [82]:
max_marks = df["Marks"].max()
print("Maximum Marks:", max_marks)

Maximum Marks: 95

In [83]:
topper = df[df["Marks"] == df["Marks"].max()]
print(topper)

    Name  Age  Marks Course
4  Sonal   20     95     CS

In [84]:
high_scorers = df[df["Marks"] > 85]
print(high_scorers)

    Name  Age  Marks Course
1   Riya   21     92     IT
3   Neha   22     88     IT
4  Sonal   20     95     CS

In [85]:
cs_students = df[df["Course"] == "CS"]
print(cs_students)

    Name  Age  Marks Course
0   Amit   20     85     CS
2  Karan   19     78     CS
4  Sonal   20     95     CS

In [86]:
above_20 = df[df["Age"] > 20]
print(above_20)

   Name  Age  Marks Course
1  Riya   21     92     IT
3  Neha   22     88     IT

In [87]:
result = df[(df["Marks"] > 85) & (df["Course"] == "CS")]
print(result)

    Name  Age  Marks Course
4  Sonal   20     95     CS